data = {   'TeeSets': [   {   'Gender': 'Male',
                       'Holes': [   {   'Allocation': 13,
                                        'HoleId': 464456,
                                        'Length': 250,
                                        'Number': 1,
                                        'Par': 4},
                                    {   'Allocation': 9,
                                        'HoleId': 464457,
                                        'Length': 300,
                                        'Number': 2,
                                        'Par': 4},
                                    {   'Allocation': 7,
                                        'HoleId': 464458,
                                        'Length': 355,
                                        'Number': 3,
                                        'Par': 4},
                                    {   'Allocation': 1,
                                        'HoleId': 464459,
                                        'Length': 365,
                                        'Number': 4,
                                        'Par': 4},
                                    {   'Allocation': 5,
                                        'HoleId': 464460,
                                        'Length': 300,
                                        'Number': 5,
                                        'Par': 4},
                                    {   'Allocation': 11,
                                        'HoleId': 464461,
                                        'Length': 475,
                                        'Number': 6,
                                        'Par': 5},
                                    {   'Allocation': 17,
                                        'HoleId': 464462,
                                        'Length': 154,
                                        'Number': 7,
                                        'Par': 3},
                                    {   'Allocation': 3,
                                        'HoleId': 464463,
                                        'Length': 355,
                                        'Number': 8,
                                        'Par': 4},
                                    {   'Allocation': 15,
                                        'HoleId': 464464,
                                        'Length': 235,
                                        'Number': 9,
                                        'Par': 4},
                                    {   'Allocation': 14,
                                        'HoleId': 464465,
                                        'Length': 162,
                                        'Number': 10,
                                        'Par': 3},
                                    {   'Allocation': 8,
                                        'HoleId': 464466,
                                        'Length': 480,
                                        'Number': 11,
                                        'Par': 5},
                                    {   'Allocation': 16,
                                        'HoleId': 464467,
                                        'Length': 125,
                                        'Number': 12,
                                        'Par': 3},
                                    {   'Allocation': 6,
                                        'HoleId': 464468,
                                        'Length': 300,
                                        'Number': 13,
                                        'Par': 4},
                                    {   'Allocation': 12,
                                        'HoleId': 464469,
                                        'Length': 154,
                                        'Number': 14,
                                        'Par': 3},
                                    {   'Allocation': 4,
                                        'HoleId': 464470,
                                        'Length': 385,
                                        'Number': 15,
                                        'Par': 4},
                                    {   'Allocation': 10,
                                        'HoleId': 464471,
                                        'Length': 500,
                                        'Number': 16,
                                        'Par': 5},
                                    {   'Allocation': 2,
                                        'HoleId': 464472,
                                        'Length': 400,
                                        'Number': 17,
                                        'Par': 4},
                                    {   'Allocation': 18,
                                        'HoleId': 464473,
                                        'Length': 146,
                                        'Number': 18,
                                        'Par': 3}],
                       'HolesNumber': 18,
                       'LegacyCRPTeeId': None,
                       'Ratings': [   {   'BogeyRating': 87.3,
                                          'CourseRating': 65.9,
                                          'RatingType': 'Total',
                                          'SlopeRating': 115.0},
                                      {   'BogeyRating': 45.6,
                                          'CourseRating': 33.8,
                                          'RatingType': 'Front',
                                          'SlopeRating': 127.0},
                                      {   'BogeyRating': 41.7,
                                          'CourseRating': 32.1,
                                          'RatingType': 'Back',
                                          'SlopeRating': 103.0}],
                       'StrokeAllocation': True,
                       'TeeSetRatingId': 227861,
                       'TeeSetRatingName': 'BLUE',
                       'TeeSetStatus': 'Active',
                       'TotalMeters': 4975,
                       'TotalPar': 70,
                       'TotalYardage': 5441},
                   {   'Gender': 'Female',
                       'Holes': [   {   'Allocation': 13,
                                        'HoleId': 247286,
                                        'Length': 276,
                                        'Number': 1,
                                        'Par': 4},
                                    {   'Allocation': 9,
                                        'HoleId': 247287,
                                        'Length': 317,
                                        'Number': 2,
                                        'Par': 4},
                                    {   'Allocation': 7,
                                        'HoleId': 247288,
                                        'Length': 365,
                                        'Number': 3,
                                        'Par': 4},
                                    {   'Allocation': 1,
                                        'HoleId': 247289,
                                        'Length': 370,
                                        'Number': 4,
                                        'Par': 4},
                                    {   'Allocation': 5,
                                        'HoleId': 247290,
                                        'Length': 321,
                                        'Number': 5,
                                        'Par': 4},
                                    {   'Allocation': 11,
                                        'HoleId': 247291,
                                        'Length': 505,
                                        'Number': 6,
                                        'Par': 5},
                                    {   'Allocation': 17,
                                        'HoleId': 247292,
                                        'Length': 160,
                                        'Number': 7,
                                        'Par': 3},
                                    {   'Allocation': 3,
                                        'HoleId': 247293,
                                        'Length': 375,
                                        'Number': 8,
                                        'Par': 5},
                                    {   'Allocation': 15,
                                        'HoleId': 247294,
                                        'Length': 235,
                                        'Number': 9,
                                        'Par': 4},
                                    {   'Allocation': 14,
                                        'HoleId': 247295,
                                        'Length': 165,
                                        'Number': 10,
                                        'Par': 3},
                                    {   'Allocation': 8,
                                        'HoleId': 247296,
                                        'Length': 505,
                                        'Number': 11,
                                        'Par': 5},
                                    {   'Allocation': 16,
                                        'HoleId': 247297,
                                        'Length': 125,
                                        'Number': 12,
                                        'Par': 3},
                                    {   'Allocation': 6,
                                        'HoleId': 247298,
                                        'Length': 328,
                                        'Number': 13,
                                        'Par': 4},
                                    {   'Allocation': 12,
                                        'HoleId': 247299,
                                        'Length': 162,
                                        'Number': 14,
                                        'Par': 3},
                                    {   'Allocation': 4,
                                        'HoleId': 247300,
                                        'Length': 394,
                                        'Number': 15,
                                        'Par': 5},
                                    {   'Allocation': 10,
                                        'HoleId': 247301,
                                        'Length': 502,
                                        'Number': 16,
                                        'Par': 5},
                                    {   'Allocation': 2,
                                        'HoleId': 247302,
                                        'Length': 401,
                                        'Number': 17,
                                        'Par': 4},
                                    {   'Allocation': 18,
                                        'HoleId': 247303,
                                        'Length': 160,
                                        'Number': 18,
                                        'Par': 3}],
                       'HolesNumber': 18,
                       'LegacyCRPTeeId': None,
                       'Ratings': [   {   'BogeyRating': 102.7,
                                          'CourseRating': 73.4,
                                          'RatingType': 'Total',
                                          'SlopeRating': 124.0},
                                      {   'BogeyRating': 49.6,
                                          'CourseRating': 35.9,
                                          'RatingType': 'Back',
                                          'SlopeRating': 116.0},
                                      {   'BogeyRating': 53.1,
                                          'CourseRating': 37.5,
                                          'RatingType': 'Front',
                                          'SlopeRating': 132.0}],
                       'StrokeAllocation': True,
                       'TeeSetRatingId': 277121,
                       'TeeSetRatingName': 'Black',
                       'TeeSetStatus': 'Active',
                       'TotalMeters': 5181,
                       'TotalPar': 72,
                       'TotalYardage': 5666},
                   {   'Gender': 'Female',
                       'Holes': [   {   'Allocation': 13,
                                        'HoleId': 464474,
                                        'Length': 250,
                                        'Number': 1,
                                        'Par': 4},
                                    {   'Allocation': 9,
                                        'HoleId': 464475,
                                        'Length': 300,
                                        'Number': 2,
                                        'Par': 4},
                                    {   'Allocation': 7,
                                        'HoleId': 464476,
                                        'Length': 355,
                                        'Number': 3,
                                        'Par': 4},
                                    {   'Allocation': 1,
                                        'HoleId': 464477,
                                        'Length': 365,
                                        'Number': 4,
                                        'Par': 4},
                                    {   'Allocation': 5,
                                        'HoleId': 464478,
                                        'Length': 300,
                                        'Number': 5,
                                        'Par': 4},
                                    {   'Allocation': 11,
                                        'HoleId': 464479,
                                        'Length': 480,
                                        'Number': 6,
                                        'Par': 5},
                                    {   'Allocation': 17,
                                        'HoleId': 464480,
                                        'Length': 157,
                                        'Number': 7,
                                        'Par': 3},
                                    {   'Allocation': 3,
                                        'HoleId': 464481,
                                        'Length': 355,
                                        'Number': 8,
                                        'Par': 5},
                                    {   'Allocation': 15,
                                        'HoleId': 464482,
                                        'Length': 235,
                                        'Number': 9,
                                        'Par': 4},
                                    {   'Allocation': 14,
                                        'HoleId': 464483,
                                        'Length': 140,
                                        'Number': 10,
                                        'Par': 3},
                                    {   'Allocation': 8,
                                        'HoleId': 464484,
                                        'Length': 444,
                                        'Number': 11,
                                        'Par': 5},
                                    {   'Allocation': 16,
                                        'HoleId': 464485,
                                        'Length': 120,
                                        'Number': 12,
                                        'Par': 3},
                                    {   'Allocation': 6,
                                        'HoleId': 464486,
                                        'Length': 300,
                                        'Number': 13,
                                        'Par': 4},
                                    {   'Allocation': 12,
                                        'HoleId': 464487,
                                        'Length': 142,
                                        'Number': 14,
                                        'Par': 3},
                                    {   'Allocation': 4,
                                        'HoleId': 464488,
                                        'Length': 374,
                                        'Number': 15,
                                        'Par': 5},
                                    {   'Allocation': 10,
                                        'HoleId': 464489,
                                        'Length': 485,
                                        'Number': 16,
                                        'Par': 5},
                                    {   'Allocation': 2,
                                        'HoleId': 464490,
                                        'Length': 400,
                                        'Number': 17,
                                        'Par': 4},
                                    {   'Allocation': 18,
                                        'HoleId': 464491,
                                        'Length': 135,
                                        'Number': 18,
                                        'Par': 3}],
                       'HolesNumber': 18,
                       'LegacyCRPTeeId': None,
                       'Ratings': [   {   'BogeyRating': 98.6,
                                          'CourseRating': 70.4,
                                          'RatingType': 'Total',
                                          'SlopeRating': 120.0},
                                      {   'BogeyRating': 46.9,
                                          'CourseRating': 33.8,
                                          'RatingType': 'Back',
                                          'SlopeRating': 111.0},
                                      {   'BogeyRating': 51.7,
                                          'CourseRating': 36.6,
                                          'RatingType': 'Front',
                                          'SlopeRating': 128.0}],
                       'StrokeAllocation': True,
                       'TeeSetRatingId': 277122,
                       'TeeSetRatingName': 'Blue',
                       'TeeSetStatus': 'Active',
                       'TotalMeters': 4880,
                       'TotalPar': 72,
                       'TotalYardage': 5337},
                   {   'Gender': 'Female',
                       'Holes': [   {   'Allocation': 13,
                                        'HoleId': 2374994,
                                        'Length': 241,
                                        'Number': 1,
                                        'Par': 4},
                                    {   'Allocation': 9,
                                        'HoleId': 2374995,
                                        'Length': 312,
                                        'Number': 2,
                                        'Par': 4},
                                    {   'Allocation': 7,
                                        'HoleId': 2374996,
                                        'Length': 290,
                                        'Number': 3,
                                        'Par': 4},
                                    {   'Allocation': 1,
                                        'HoleId': 2374997,
                                        'Length': 340,
                                        'Number': 4,
                                        'Par': 4},
                                    {   'Allocation': 5,
                                        'HoleId': 2374998,
                                        'Length': 294,
                                        'Number': 5,
                                        'Par': 4},
                                    {   'Allocation': 11,
                                        'HoleId': 2374999,
                                        'Length': 357,
                                        'Number': 6,
                                        'Par': 5},
                                    {   'Allocation': 17,
                                        'HoleId': 2375000,
                                        'Length': 143,
                                        'Number': 7,
                                        'Par': 3},
                                    {   'Allocation': 3,
                                        'HoleId': 2375001,
                                        'Length': 355,
                                        'Number': 8,
                                        'Par': 5},
                                    {   'Allocation': 15,
                                        'HoleId': 2375002,
                                        'Length': 216,
                                        'Number': 9,
                                        'Par': 4},
                                    {   'Allocation': 14,
                                        'HoleId': 2375003,
                                        'Length': 130,
                                        'Number': 10,
                                        'Par': 3},
                                    {   'Allocation': 8,
                                        'HoleId': 2375004,
                                        'Length': 374,
                                        'Number': 11,
                                        'Par': 5},
                                    {   'Allocation': 16,
                                        'HoleId': 2375005,
                                        'Length': 120,
                                        'Number': 12,
                                        'Par': 3},
                                    {   'Allocation': 6,
                                        'HoleId': 2375006,
                                        'Length': 300,
                                        'Number': 13,
                                        'Par': 4},
                                    {   'Allocation': 12,
                                        'HoleId': 2375007,
                                        'Length': 135,
                                        'Number': 14,
                                        'Par': 3},
                                    {   'Allocation': 4,
                                        'HoleId': 2375008,
                                        'Length': 385,
                                        'Number': 15,
                                        'Par': 5},
                                    {   'Allocation': 10,
                                        'HoleId': 2375009,
                                        'Length': 405,
                                        'Number': 16,
                                        'Par': 5},
                                    {   'Allocation': 2,
                                        'HoleId': 2375010,
                                        'Length': 346,
                                        'Number': 17,
                                        'Par': 4},
                                    {   'Allocation': 18,
                                        'HoleId': 2375011,
                                        'Length': 146,
                                        'Number': 18,
                                        'Par': 3}],
                       'HolesNumber': 18,
                       'LegacyCRPTeeId': None,
                       'Ratings': [   {   'BogeyRating': 95.7,
                                          'CourseRating': 68.2,
                                          'RatingType': 'Total',
                                          'SlopeRating': 118.0},
                                      {   'BogeyRating': 46.5,
                                          'CourseRating': 33.3,
                                          'RatingType': 'Back',
                                          'SlopeRating': 113.0},
                                      {   'BogeyRating': 49.2,
                                          'CourseRating': 34.9,
                                          'RatingType': 'Front',
                                          'SlopeRating': 122.0}],
                       'StrokeAllocation': True,
                       'TeeSetRatingId': 277123,
                       'TeeSetRatingName': 'YAGAW',
                       'TeeSetStatus': 'Active',
                       'TotalMeters': 4471,
                       'TotalPar': 72,
                       'TotalYardage': 4889},
                   {   'Gender': 'Female',
                       'Holes': [   {   'Allocation': 13,
                                        'HoleId': 1120340,
                                        'Length': 220,
                                        'Number': 1,
                                        'Par': 4},
                                    {   'Allocation': 9,
                                        'HoleId': 1120341,
                                        'Length': 278,
                                        'Number': 2,
                                        'Par': 4},
                                    {   'Allocation': 7,
                                        'HoleId': 1120342,
                                        'Length': 290,
                                        'Number': 3,
                                        'Par': 4},
                                    {   'Allocation': 1,
                                        'HoleId': 1120343,
                                        'Length': 300,
                                        'Number': 4,
                                        'Par': 4},
                                    {   'Allocation': 5,
                                        'HoleId': 1120344,
                                        'Length': 294,
                                        'Number': 5,
                                        'Par': 4},
                                    {   'Allocation': 11,
                                        'HoleId': 1120345,
                                        'Length': 357,
                                        'Number': 6,
                                        'Par': 5},
                                    {   'Allocation': 17,
                                        'HoleId': 1120346,
                                        'Length': 137,
                                        'Number': 7,
                                        'Par': 3},
                                    {   'Allocation': 3,
                                        'HoleId': 1120347,
                                        'Length': 295,
                                        'Number': 8,
                                        'Par': 5},
                                    {   'Allocation': 15,
                                        'HoleId': 1120348,
                                        'Length': 204,
                                        'Number': 9,
                                        'Par': 4},
                                    {   'Allocation': 14,
                                        'HoleId': 1120349,
                                        'Length': 130,
                                        'Number': 10,
                                        'Par': 3},
                                    {   'Allocation': 8,
                                        'HoleId': 1120350,
                                        'Length': 374,
                                        'Number': 11,
                                        'Par': 5},
                                    {   'Allocation': 16,
                                        'HoleId': 1120351,
                                        'Length': 115,
                                        'Number': 12,
                                        'Par': 3},
                                    {   'Allocation': 6,
                                        'HoleId': 1120352,
                                        'Length': 245,
                                        'Number': 13,
                                        'Par': 4},
                                    {   'Allocation': 12,
                                        'HoleId': 1120353,
                                        'Length': 135,
                                        'Number': 14,
                                        'Par': 3},
                                    {   'Allocation': 4,
                                        'HoleId': 1120354,
                                        'Length': 370,
                                        'Number': 15,
                                        'Par': 5},
                                    {   'Allocation': 10,
                                        'HoleId': 1120355,
                                        'Length': 395,
                                        'Number': 16,
                                        'Par': 5},
                                    {   'Allocation': 2,
                                        'HoleId': 1120356,
                                        'Length': 335,
                                        'Number': 17,
                                        'Par': 4},
                                    {   'Allocation': 18,
                                        'HoleId': 1120357,
                                        'Length': 130,
                                        'Number': 18,
                                        'Par': 3}],
                       'HolesNumber': 18,
                       'LegacyCRPTeeId': None,
                       'Ratings': [   {   'BogeyRating': 93.5,
                                          'CourseRating': 66.5,
                                          'RatingType': 'Total',
                                          'SlopeRating': 115.0},
                                      {   'BogeyRating': 45.6,
                                          'CourseRating': 32.6,
                                          'RatingType': 'Back',
                                          'SlopeRating': 110.0},
                                      {   'BogeyRating': 47.9,
                                          'CourseRating': 33.9,
                                          'RatingType': 'Front',
                                          'SlopeRating': 119.0}],
                       'StrokeAllocation': True,
                       'TeeSetRatingId': 277124,
                       'TeeSetRatingName': 'Green',
                       'TeeSetStatus': 'Active',
                       'TotalMeters': 4210,
                       'TotalPar': 72,
                       'TotalYardage': 4604},
                   {   'Gender': 'Male',
                       'Holes': [   {   'Allocation': 13,
                                        'HoleId': 247268,
                                        'Length': 276,
                                        'Number': 1,
                                        'Par': 4},
                                    {   'Allocation': 9,
                                        'HoleId': 247269,
                                        'Length': 329,
                                        'Number': 2,
                                        'Par': 4},
                                    {   'Allocation': 7,
                                        'HoleId': 247270,
                                        'Length': 376,
                                        'Number': 3,
                                        'Par': 4},
                                    {   'Allocation': 1,
                                        'HoleId': 247271,
                                        'Length': 386,
                                        'Number': 4,
                                        'Par': 4},
                                    {   'Allocation': 5,
                                        'HoleId': 247272,
                                        'Length': 321,
                                        'Number': 5,
                                        'Par': 4},
                                    {   'Allocation': 11,
                                        'HoleId': 247273,
                                        'Length': 505,
                                        'Number': 6,
                                        'Par': 5},
                                    {   'Allocation': 17,
                                        'HoleId': 247274,
                                        'Length': 184,
                                        'Number': 7,
                                        'Par': 3},
                                    {   'Allocation': 3,
                                        'HoleId': 247275,
                                        'Length': 390,
                                        'Number': 8,
                                        'Par': 4},
                                    {   'Allocation': 15,
                                        'HoleId': 247276,
                                        'Length': 245,
                                        'Number': 9,
                                        'Par': 4},
                                    {   'Allocation': 14,
                                        'HoleId': 247277,
                                        'Length': 175,
                                        'Number': 10,
                                        'Par': 3},
                                    {   'Allocation': 8,
                                        'HoleId': 247278,
                                        'Length': 505,
                                        'Number': 11,
                                        'Par': 5},
                                    {   'Allocation': 16,
                                        'HoleId': 247279,
                                        'Length': 135,
                                        'Number': 12,
                                        'Par': 3},
                                    {   'Allocation': 6,
                                        'HoleId': 247280,
                                        'Length': 328,
                                        'Number': 13,
                                        'Par': 4},
                                    {   'Allocation': 12,
                                        'HoleId': 247281,
                                        'Length': 172,
                                        'Number': 14,
                                        'Par': 3},
                                    {   'Allocation': 4,
                                        'HoleId': 247282,
                                        'Length': 404,
                                        'Number': 15,
                                        'Par': 4},
                                    {   'Allocation': 10,
                                        'HoleId': 247283,
                                        'Length': 519,
                                        'Number': 16,
                                        'Par': 5},
                                    {   'Allocation': 2,
                                        'HoleId': 247284,
                                        'Length': 419,
                                        'Number': 17,
                                        'Par': 4},
                                    {   'Allocation': 18,
                                        'HoleId': 247285,
                                        'Length': 164,
                                        'Number': 18,
                                        'Par': 3}],
                       'HolesNumber': 18,
                       'LegacyCRPTeeId': None,
                       'Ratings': [   {   'BogeyRating': 90.8,
                                          'CourseRating': 68.1,
                                          'RatingType': 'Total',
                                          'SlopeRating': 123.0},
                                      {   'BogeyRating': 43.4,
                                          'CourseRating': 33.2,
                                          'RatingType': 'Back',
                                          'SlopeRating': 110.0},
                                      {   'BogeyRating': 47.4,
                                          'CourseRating': 34.9,
                                          'RatingType': 'Front',
                                          'SlopeRating': 135.0}],
                       'StrokeAllocation': True,
                       'TeeSetRatingId': 514467,
                       'TeeSetRatingName': 'BLACK',
                       'TeeSetStatus': 'Active',
                       'TotalMeters': 5334,
                       'TotalPar': 70,
                       'TotalYardage': 5833}]
}